### ISSUE TITLE
2.1.26 breaks the ability to join servers hosted by Windows players

### ISSUE THREAD

**Issue by vyvir** [P-AS/srb2-legacy#13]
The change of the version is now preventing players from joining servers hosted by 2.1.25 players

**Comment by P-AS** [comment]
What specifically happens when you try to join? I've considered adding an option to spoof 2.1.25, but I couldn't test netplay.

**Comment by vyvir** [comment]
It just gets stuck like this
![image](https://github.com/user-attachments/assets/643bae8d-76c1-4761-90df-83ed48a4d5f7)

**Comment by vyvir** [comment]
2.1.25 works on the other hand

**Comment by chromaticpipe** [comment]
This is simply due to the version change and nothing else, you can manually downgrade all the version stuff to match 2.1.25 and it will work when joining 2.1.25 netgames

**Comment by P-AS** [comment]
Fixed by ef9fdde. Just type `netcompat on` in the console to spoof a 2.1.25 client.
